### ISSUE TITLE
Tried to compile on debian buster. dpkg -i returns errors

### ISSUE THREAD

**Issue by DominikRzecki** [CalcProgrammer1/openrgb-dkms-drivers#1]
gedit /var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/make.log

DKMS make.log for openrgb-dkms-drivers-5.6.4 for kernel 4.19.0-9-amd64 (x86_64)
Sat 20 Jun 2020 02:54:00 PM CEST
make -C /lib/modules/4.19.0-9-amd64/build M=/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-9-amd64'
  CC [M]  /var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.o
  CC [M]  /var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-nct6775.o
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c: In function ‘piix4_setup_sb800’:
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:287:28: error: ‘PCI_VENDOR_ID_HYGON’ undeclared (first use in this function); did you mean ‘PCI_VENDOR_ID_EICON’?
      (PIIX4_dev->vendor == PCI_VENDOR_ID_HYGON &&
                            ^~~~~~~~~~~~~~~~~~~
                            PCI_VENDOR_ID_EICON
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:287:28: note: each undeclared identifier is reported only once for each function it appears in
In file included from /var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:26:
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c: At top level:
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:792:15: error: ‘PCI_VENDOR_ID_HYGON’ undeclared here (not in a function); did you mean ‘PCI_VENDOR_ID_EICON’?
  { PCI_DEVICE(PCI_VENDOR_ID_HYGON, PCI_DEVICE_ID_AMD_KERNCZ_SMBUS) },
               ^~~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-4.19.0-9-common/include/linux/pci.h:784:13: note: in definition of macro ‘PCI_DEVICE’
  .vendor = (vend), .device = (dev), \
             ^~~~
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c: In function ‘piix4_probe’:
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:923:18: warning: comparison between pointer and integer
      dev->vendor == PCI_VENDOR_ID_HYGON) {
                  ^~
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:928:20: warning: comparison between pointer and integer
        dev->vendor == PCI_VENDOR_ID_HYGON) &&
                    ^~
make[4]: *** [/usr/src/linux-headers-4.19.0-9-common/scripts/Makefile.build:315: /var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/src/linux-headers-4.19.0-9-common/Makefile:1537: _module_/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-9-amd64'
make: *** [Makefile:15: default] Error 2

**Comment by raketexyz** [comment]
Same issue here.

DKMS make.log for openrgb-dkms-drivers-5.6.4 for kernel 4.19.0-9-amd64 (x86_64)
Sun 28 Jun 2020 05:03:43 AM CEST
make -C /lib/modules/4.19.0-9-amd64/build M=/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-9-amd64'
  CC [M]  /var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.o
  CC [M]  /var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-nct6775.o
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c: In function ‘piix4_setup_sb800’:
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:287:28: error: ‘PCI_VENDOR_ID_HYGON’ undeclared (first use in this function); did you mean ‘PCI_VENDOR_ID_EICON’?
      (PIIX4_dev->vendor == PCI_VENDOR_ID_HYGON &&
                            ^~~~~~~~~~~~~~~~~~~
                            PCI_VENDOR_ID_EICON
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:287:28: note: each undeclared identifier is reported only once for each function it appears in
In file included from /var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:26:
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c: At top level:
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:792:15: error: ‘PCI_VENDOR_ID_HYGON’ undeclared here (not in a function); did you mean ‘PCI_VENDOR_ID_EICON’?
  { PCI_DEVICE(PCI_VENDOR_ID_HYGON, PCI_DEVICE_ID_AMD_KERNCZ_SMBUS) },
               ^~~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-4.19.0-9-common/include/linux/pci.h:784:13: note: in definition of macro ‘PCI_DEVICE’
  .vendor = (vend), .device = (dev), \
             ^~~~
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c: In function ‘piix4_probe’:
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:923:18: warning: comparison between pointer and integer
      dev->vendor == PCI_VENDOR_ID_HYGON) {
                  ^~
/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.c:928:20: warning: comparison between pointer and integer
        dev->vendor == PCI_VENDOR_ID_HYGON) &&
                    ^~
make[4]: *** [/usr/src/linux-headers-4.19.0-9-common/scripts/Makefile.build:315: /var/lib/dkms/openrgb-dkms-drivers/5.6.4/build/i2c-piix4.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/src/linux-headers-4.19.0-9-common/Makefile:1537: _module_/var/lib/dkms/openrgb-dkms-drivers/5.6.4/build] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-9-amd64'
make: *** [Makefile:15: default] Error 2

**Comment by CalcProgrammer1** [comment]
Probably using too old of a kernel.  Upgrade to a newer kernel (5.6 or newer, as it looks like the patch was against 5.6.4) and then try.
